### ISSUE TITLE
Local_position reference alt when using External vision

### ISSUE THREAD

**Issue by devbharat** [PX4/ecl#103]
When the GPS is connected to the pixhawk and the GPS module is started, but external vision is enabled for position and altitude instead of GPS, the reference altitude of local position somehow also drifts with the GPS value(indoors). Turning off the GPS module or disconnecting it solves the issue.

I suspect its the estimators "_gps_alt_ref" value is leaking in from GPS somehow.

**Comment by priseborough** [comment]
Can you please provide a replay log from a flight where this behaviour is demonstrated.

**Comment by devbharat** [comment]
This was from the code long ago, I haven't been up to testing recently. I'll see if I can recreate it and post update here.

**Comment by priseborough** [comment]
Bump

**Comment by devbharat** [comment]
I really do not have the resources now to conduct this test outdoors. Either we let this hang till I get the dataset with the temperory solution being disabling GPS when using vision, or we close it and reopen if the issue is observed again.
