### ISSUE TITLE
can anyone please  help me for better height estimation with baro  and rangefinder for multiple vehicle as of now they are not at same height in offboard

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/ecl#1030]

**Comment by airsimdevdd** [comment]
is it parameter problem or firmware level modifcations or hardware issue please help me out

**Comment by bresch** [comment]
ECL is now merged into [PX4-Autopilot](https://github.com/PX4/PX4-Autopilot/issues). Please ask your questions there directly. And please, provide a more detailed question than just a title, otherwise no one will be able to help you.
