### ISSUE TITLE
External vision XY initialization and tracking

### ISSUE THREAD

**Issue by devbharat** [PX4/ecl#109]
At initialization LPOS.X and LPOS.Y take way too long to converge to values sent by external vision. (Probably because aircraft is stationary but not at origin when EKF2 starts, so external vision is sending in non zero values). Need to support starting at non zero values.

![lposxy_initialization](https://cloud.githubusercontent.com/assets/3105122/14832230/7a96f23c-0bf9-11e6-9c28-2c29d6e3cdc1.png)

And they oscillate on external vision reset to new value:
![lposxy_resetoscillatoin](https://cloud.githubusercontent.com/assets/3105122/14832309/e439bc10-0bf9-11e6-9ff6-dd3317f58348.png)

External vision data is fused with 1cm variance.

**Comment by devbharat** [comment]
Full log file can be found at http://wikisend.com/download/174296/log001.px4log

**Comment by priseborough** [comment]
Fixed in master
