### ISSUE TITLE
altitude estimate diverges when fusing airspeed data

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#121]
@tumbili 
From two flights with the wingwing
![3](https://cloud.githubusercontent.com/assets/7795133/15040596/56726fe4-12b6-11e6-8a9e-57347362abc7.png)
![4](https://cloud.githubusercontent.com/assets/7795133/15040598/58fc4f64-12b6-11e6-90d8-22d9008cd2f4.png)

The raw airspeed sensor data doesn't look so nice so will try to replace the airspeed sensor and level shifter with a new one from AUAV and try again.

**Comment by LorenzMeier** [comment]
@CarlOlsson Can you have a look at this here? The code before Daniel's fix looks wrong to me, and I would not be surprised if that results in what you're seeing here:
https://github.com/PX4/ecl/pull/120/files

**Comment by LorenzMeier** [comment]
@CarlOlsson Can you share the raw log file via Log muncher?

And can you please do a flight again with replay logging?

**Comment by CarlOlsson** [comment]
Will do the two flights tomorrow and share the logs. Just want to make sure the sensor is working correctly first

**Comment by CarlOlsson** [comment]
First flight today
![2](https://cloud.githubusercontent.com/assets/7795133/15068358/f875f7f0-1376-11e6-8812-ded6fd845982.png)
![1](https://cloud.githubusercontent.com/assets/7795133/15068359/f9c24d52-1376-11e6-9218-c1c769b9108c.png)
Logs here:
http://logs.uaventure.com/view/F2SnAfAwav576JyfqmLeQe
http://logs.uaventure.com/logmuncher/charts/F2SnAfAwav576JyfqmLeQe/logmuncher.log

**Comment by CarlOlsson** [comment]
Made a second flight, deactivated airspeed fusion completely. Ekf still diverges.
![1](https://cloud.githubusercontent.com/assets/7795133/15072823/ecdd2ffc-1395-11e6-90d1-2d388700cd3f.png)
http://logs.uaventure.com/view/eVXyzfzw2oryqRJNvuumC3
http://logs.uaventure.com/logmuncher/charts/eVXyzfzw2oryqRJNvuumC3/logmuncher.log

**Comment by LorenzMeier** [comment]
Did you create the replay logs as requested? Without that more flights are relatively pointless.

**Comment by CarlOlsson** [comment]
Yesterday I flight tested ecl master and this pr PX4/firmware#4484
![1](https://cloud.githubusercontent.com/assets/7795133/15137253/c2ef0c74-1688-11e6-9a6f-da3c7872ad16.png)
![2](https://cloud.githubusercontent.com/assets/7795133/15137256/c46e7634-1688-11e6-9d63-d60830cf93a4.png)
Unfortunately the RPL logs seems corrupt will try to fix it as soon as possible

**Comment by CarlOlsson** [comment]
Plots: http://logs.uaventure.com/view/2y6aLea2BuiXQSeXe9zYHZ
Log: http://logs.uaventure.com/logmuncher/charts/2y6aLea2BuiXQSeXe9zYHZ/logmuncher.log

**Comment by CarlOlsson** [comment]
I remounted the pixracer such that it is damping vibrations.
Now the altitude is not diverging anymore
![1](https://cloud.githubusercontent.com/assets/7795133/15150714/b01c3cfc-16ce-11e6-8c4f-b14f30370ae1.png)

**Comment by CarlOlsson** [comment]
![1](https://cloud.githubusercontent.com/assets/7795133/15158567/d5c730b6-16f0-11e6-875f-d2f05648c302.jpg)
![2](https://cloud.githubusercontent.com/assets/7795133/15158568/d5ded73e-16f0-11e6-8786-e60586d26d94.jpg)
![3](https://cloud.githubusercontent.com/assets/7795133/15158569/d5e8327a-16f0-11e6-8078-b7c2e2da3fdf.jpg)
