### ISSUE TITLE
RPL logs with airspeed sensor

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#126]
Did two flights with the wingwing
![img_8696 1](https://cloud.githubusercontent.com/assets/7795133/15172961/6ca4ba40-1759-11e6-90d8-9e8a65716b1d.JPG)

**First flight**
Plots: http://logs.uaventure.com/view/8gD2HCcvqjobKm5Bq46Yei
Log: http://logs.uaventure.com/logmuncher/charts/8gD2HCcvqjobKm5Bq46Yei/logmuncher.log

**Second flight**
Plots: http://logs.uaventure.com/view/hbXUjHrcGHQm9Dpuxxcv5d
Log: http://logs.uaventure.com/logmuncher/charts/hbXUjHrcGHQm9Dpuxxcv5d/logmuncher.log

@priseborough @tumbili 
Would be very happy for any comments on the logs

**Comment by priseborough** [comment]
What version of the code were you using and have you isolated your pixracer from vibration yet?

**Comment by CarlOlsson** [comment]
Yes the board is isolated #121
I was using this branch
0d377dc5f4ddbfd05af5d6e66cdac38e0ff49a3d
https://github.com/CarlOlsson/Firmware/tree/add_airspeed_to_rpl
I have a problem with the replay logs. If I activate airspeed fusion I still don't get any airspeed innovations in the logs. Even though I get it with the same code in SITL. @tumbili thought it could be something with how the flags in the estimator are logged. My idea now is to do another test with current master and post an issue about it if it persists.

**Comment by CarlOlsson** [comment]
See PX4/Firmware#4515

**Comment by priseborough** [comment]
What is the highest linear or rotational natural frequency of your isolation system and is there anything that could be bypassing it?

**Comment by CarlOlsson** [comment]
The pixracer is mounted on 4 silicone tubes like this:
![fullsizerender 1](https://cloud.githubusercontent.com/assets/7795133/15210895/a95579e0-1838-11e6-81ef-c028749ffaa1.jpg)
I am not sure if that answers your question? Otherwise please explain a bit more and I will do some measurements if required

**Comment by CarlOlsson** [comment]
ekf2 replay is finally working with airspeed.
![1](https://cloud.githubusercontent.com/assets/7795133/15218180/ff3335ca-185e-11e6-8a8a-7a3d108886a1.png)
@priseborough @tumbili I am a bit confused of the innovations before we are airborne, would appreciate any comments!

**Comment by CarlOlsson** [comment]
Here is a mission flown in SITL. The vtol takes of flies for some time, transitions to hover and then transitions back to cruise.
![1](https://cloud.githubusercontent.com/assets/7795133/15241549/07e4c700-18f1-11e6-8878-60510c20dbfd.png)
The innovations of the fused tas shoud be zero during hover but they are not

**Comment by tumbili** [comment]
@CarlOlsson Remember that when nothing is fused the innovation will just remain constant at the last value. Maybe this is why you are seeing innovations during hover.

**Comment by CarlOlsson** [comment]
Yea you are right. No innovations are published during hover but the postprocessing sw fills up the missing data points with the last value. Would you recommend to keep it this way?

**Comment by priseborough** [comment]
@CarlOlsson, those mounts are too stiff for a board of such low mass. You need to get the vibration modes below 50Hz. I use a thin ply mounting plate with 4 8x8x6 mm low density latex foam squares as shown below:
![photo on 17-05-2016 at 4 56 pm](https://cloud.githubusercontent.com/assets/3596952/15313727/7af63e06-1c50-11e6-9479-6fc001b25a65.jpg)
