### ISSUE TITLE
Initialization in SITL is slow

### ISSUE THREAD

**Issue by julianoes** [PX4/ecl#128]
The initialization in SITL is painfully slow and consumes a lot of time for developers.

The two delays to wait for are:
- ekf2 initialized
- home position initialized

Presumably both are due to the rather slow startup of ekf2.

It would be nicer to have this faster, or at least use a hack to speed it up for SITL.

**Comment by priseborough** [comment]
https://github.com/PX4/ecl/pull/134

**Comment by priseborough** [comment]
@julianoes If this PR is able to resolve your issues (in combination with parameter changes) then I will pull in the PR and close this issue.

**Comment by priseborough** [comment]
Fixed in master
