### ISSUE TITLE
Specifying desired height sensor

### ISSUE THREAD

**Issue by pickledgator** [PX4/ecl#151]
Per [control.cpp#L452-L470](https://github.com/PX4/ecl/blob/e2d9e19a5dde27e8db0d8f838ddd614bfd4b0f1b/EKF/control.cpp#L452-L470), what is the motivation for adding the _control_status.flags.XX as logical ors inside the if/else statements for baro/gps? Are we trying to limit the height sensor fusion to one sensor only or fuse all that are available? 

If the prior, seems to make sense to add add a param check for VDIST_SENSOR_EV (which exists in the enum already) to the first if statement and remove the _control_status.flags checks for baro/gps. If the later is the case, what purpose does the _params.vdist_sensor_type serve?

**Comment by priseborough** [comment]
The original intention was to provide a structure to allow fusion of multiple height sources, but the height offsets were problematic unless additional states were added
