### ISSUE TITLE
 Separate filter monitoring function for GPS quality

### ISSUE THREAD

**Issue by bugobliterator** [PX4/ecl#18]
Addition of a separate filter monitoring function that looks at GPS innovations, eph, epv, speed accuracy, number of satellites, position variances, etc to determine if 
a) Is the GPS solution is good enough to set an origin
b) Provide a position accuracy estimate to the system
c) Provide a dead-reckoning status to the system
d) Provide a validity status for the different states (eg attitude, hvel, hpos, vvel, vpos, wind, etc)
e) Provide position glitch warning to the system

**Comment by priseborough** [comment]
Partially addressed by https://github.com/PX4/ecl/pull/14

**Comment by priseborough** [comment]
outstanding items dupicaed by #32
