### ISSUE TITLE
Add reference papers as pdfs to this repo

### ISSUE THREAD

**Issue by mkschreder** [PX4/ecl#187]
It would be very helpful to have a set of reference papers (PDFs) to follow when understanding implementation of this estimator. 

Can you push them all into a folder called "references"?

**Comment by 1102sc** [comment]
I think it's very necessary.

**Comment by 1102sc** [comment]
I think it's very necessary.

**Comment by xuyongzhi** [comment]
It would be great help!

**Comment by priseborough** [comment]
I have provided some slides and included list of references that I have found useful.
