### ISSUE TITLE
Implementation of simpler magnetic heading fusion pre takeoff

### ISSUE THREAD

**Issue by bugobliterator** [PX4/ecl#20]
The simpler magnetic heading fusion should be used when on the ground or indoors, with a transition to use of 3-axis magnetometer fusion for up and away flight. This is because the simple magnetic heading fusion is more robust to external field disturbances, whereas the 3-axis fusion is more robust to sensor errors and provides improved angular accuracy when the assumption of a consistent external field is true.

**Comment by priseborough** [comment]
Fixed by https://github.com/PX4/ecl/pull/35
