### ISSUE TITLE
Optical flow support

### ISSUE THREAD

**Issue by bugobliterator** [PX4/ecl#21]

**Comment by bugobliterator** [comment]
https://github.com/bugobliterator/ecl/tree/pr-optflow

**Comment by tumbili** [comment]
@bugobliterator Had a look at your branch, looks good! Do you want to open an PR for this?
I'd love to try optical flow soon.

**Comment by bugobliterator** [comment]
I am still working on it. I have setup SITL to test it. Will be doing some flight tests too if possible before creating a PR.

**Comment by tumbili** [comment]
@bugobliterator Ok great! Are you using the PX4 gazebo simulation?

**Comment by bugobliterator** [comment]
yes

**Comment by priseborough** [comment]
completed with #74
