### ISSUE TITLE
Cmake lists error

### ISSUE THREAD

**Issue by FarmerLjx** [PX4/ecl#240]
Open as a CLion project, and get this output by Cmake:

CMake Error at CMakeLists.txt:37 (px4_add_module):
  Unknown CMake command "px4_add_module".

**Comment by psiphi75** [comment]
I get the same issue.  I just want to compile the files in `elc/EKF/tests/base/`.  I run 'cmake ./` from that folder and get:

```sh
CMake Error at CMakeLists.txt:33 (px4_add_module):
  Unknown CMake command "px4_add_module".
```

**Comment by dagar** [comment]
The current top level CMakeLists.txt is used for including ecl in PX4 Firmware. If you want to build EKF2 standalone use EKF/CMakeLists.txt or run build.sh.

**Comment by FarmerLjx** [comment]
build.sh worked for me, but made some changes to eliminate compilation errors.

diff --git a/EKF/CMakeLists.txt b/EKF/CMakeLists.txt
index 0d7d6a9..cb3b107 100644
--- a/EKF/CMakeLists.txt
+++ b/EKF/CMakeLists.txt
@@ -66,6 +66,8 @@ set(SRCS
        mag_fusion.cpp
        gps_checks.cpp
        airspeed_fusion.cpp
+       optflow_fusion.cpp
+       terrain_estimator.cpp

**Comment by dagar** [comment]
@FarmerLjx can you open a pull request?

**Comment by FarmerLjx** [comment]
It is just add two source files to the *SRCS*, so really need a pull request? I'm still learning how to use my data to test the effect of EKF.

**Comment by dagar** [comment]
That's how anyone, including developers with write access to the repository
would make this small change.

**Comment by FarmerLjx** [comment]
Ok, i see, thanks!
