### ISSUE TITLE
State flow after GPS loss

### ISSUE THREAD

**Issue by bugobliterator** [PX4/ecl#27]
If GPS is lost, then a maximum dead-reckoning time must be observed, at which time the filter will need to be switched into its non-aiding mode of operation to prevent loss of attitude reference.

If the innovation consistency check on GPs position has failed for long enough that the horizontal position uncertainty has reached a user specified size, then the states should be reset to the GPS position. This is to stop bad inertial data causing permanent loss of GPs fusion which can happen if the inertial solution errors are growing faster than the innovation consistency gate.

**Comment by priseborough** [comment]
Fixed by https://github.com/PX4/ecl/pull/35

**Comment by priseborough** [comment]
Fixed by https://github.com/PX4/ecl/pull/35

**Comment by priseborough** [comment]
https://github.com/PX4/ecl/pull/35
