### ISSUE TITLE
Vision Position constantly re-initializing

### ISSUE THREAD

**Issue by lachyd** [PX4/ecl#296]
Using vision position constantly prints out "EKF commencing external vision position fusion", and resets the estimator.

I believe the fix is to add the following directly after line 152 of control.cpp (where it says resetHeight();):

_control_status.flags.ev_pos=true;

This follows the same convention as the ev_yaw conditional below it and works well in simulation.

**Comment by mhkabir** [comment]
@lachyd How are you simulating vision estimates in simulation?

**Comment by lachyd** [comment]
Using gazebo and ROS. I have a laser scanner mounted on the drone in my gazebo model, which I feed into an SLAM algo and pass the resulting coordinates to PX4 via the mavros vision position topic.

**Comment by mhkabir** [comment]
What Z position measurement are you sending with the pose? The scanner only gives you a 2D estimate.

**Comment by lachyd** [comment]
I'm using a rangefinder for the Z measurement.

**Comment by mhkabir** [comment]
Makes sense. Can you please send in a pull request with your fixes?

**Comment by lachyd** [comment]
Done, thanks!
