### ISSUE TITLE
reset height when switching to range finder?

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/ecl#302]
@jlecoeur would prefer something like

if (_control_status_prev.flags.rng_hgt != _control_status.flags.rng_hgt) {
 resetHeight();
 _hgt_sensor_offset = _params.rng_gnd_clearance;
}
instead of https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L777-L786.
To summarize, he's worried that _state.pos(2) does not estimate height when range is primary, as suggested in the doc.

**Comment by jlecoeur** [comment]
Thanks for opening this @ChristophTobler, it can indeed be discussed separately.
