### ISSUE TITLE
CI environment is failing due to pyenv deprecation

### ISSUE THREAD

**Issue by priseborough** [PX4/ecl#332]
https://travis-ci.org/PX4/ecl/jobs/283460861

**Comment by dagar** [comment]
@PeterDuerr any suggestions for fixing travis-ci?

![image](https://user-images.githubusercontent.com/84712/31446413-fc4e2602-ae6d-11e7-8667-6bac6412e711.png)

**Comment by dagar** [comment]
Partially fixed. https://github.com/PX4/ecl/pull/344

**Comment by dagar** [comment]
I've created a docker container (https://hub.docker.com/r/px4io/px4-dev-ecl/) that contains these dependencies.
