### ISSUE TITLE
baro_innov_gate also controls gps gate size for height fusion

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#336]
Should we really use the baro gate size [here](https://github.com/PX4/ecl/blob/master/EKF/vel_pos_fusion.cpp#L180), if so we should update the parameter description

**Comment by priseborough** [comment]
Agree, both the variable name and description should be updated. I will create a PR for this.

**Comment by priseborough** [comment]
Fixed in ecl.
