### ISSUE TITLE
Incomplete magnetometer and heading fusion tuning parameter implementation

### ISSUE THREAD

**Issue by priseborough** [PX4/ecl#34]
The heading fusion observation noise parameter EKF2_HEAD_NOISE adjusts the observation variance, not the observation noise. It should be adjusting noise and have units of rad
The magnetometer noise parameter EKF2_MAG_NOISE ias actually adjusting the magnetic field state process noise, nor the magnetometer observation noise. It should be renamed.
There is no parameter to adjust the magnetometer observation noise
There is no parameter to control which magnetometer fusion method is used. A suggestion is to provide three options
1) Auto selection (default)
2) Always used heading fusion
3) Always use 3-axis field fusion

**Comment by priseborough** [comment]
Addressed by #36

**Comment by tumbili** [comment]
Applied to master, closing.
