### ISSUE TITLE
Attitude estimate when no gps and magnetic fusion

### ISSUE THREAD

**Issue by xmutrue** [PX4/ecl#349]
Will attitude estimate still works fine when no gps fusion and bad magnetic ?

It seems that ECL do not take the accelerometer into observation like ahrs.

Many thanks @priseborough

**Comment by priseborough** [comment]
Without any external aiding it falls back to a mode where a static position is fused to constrain drift in roll and pitch. This mode is used before GP checks pass and for flying indoors.

**Comment by xmutrue** [comment]
If the fixedwing uav fly outdoors,  and when gps failure, it means that the attitude control of uav can't work well.  
Like other gps/ins product, it will change from gps/ins mode to ahrs mode to provide the pitch and roll for vehicle, and the Controller can use the dead reckoning with airspeed to calculate position.

**Comment by priseborough** [comment]
If it has airspeed, and sideslip fusion has also been enabled, then it will dead-reckon. However the PX4 commander failsafe does not yet support this capability fully and will still fall back out of attitude control, requiring the operator to select a non position controlled flight mode. No waypoint controlled flight modes can be used when it is dead-reckoning.

See testing here: https://github.com/PX4/ecl/pull/339

There has been no previous interest in funding development to support use on fixed wing platforms without GPS and airspeed sensing.

**Comment by xmutrue** [comment]
I wonder if the ECL has been port to other platform except the ardupilot and px4.

**Comment by itayguy** [comment]
Does PX4 has dead reckoning like ardupilot  for copter ?
