### ISSUE TITLE
Accel bias variance is logged as zeros

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#370]
@priseborough 
This log file is from a race quad, is it intended behavior that we set the accel bias variance to zero?
![image](https://user-images.githubusercontent.com/7795133/34079994-e7ffb522-e337-11e7-8a6f-5f9c098de55c.png)
![image](https://user-images.githubusercontent.com/7795133/34079995-e9be090e-e337-11e7-825f-e67b51385442.png)

[logfile](https://logs.px4.io/plot_app?log=b3ba82be-4b0a-46f1-b00b-561abda0536c)
Code was px4 master (e8624f8afe6199fa8dc9ee1bfc74ac8f6ef52117) with some minor changes to rcS

**Comment by priseborough** [comment]
It is expected behaviour to protect against bad learning of bias values if there are high manoeuvre levels. See https://github.com/PX4/ecl/blob/master/EKF/covariance.cpp#L160

**Comment by CarlOlsson** [comment]
Ah okey thanks, I had missed that
