### ISSUE TITLE
code writing error in TECS.CPP 

### ISSUE THREAD

**Issue by yuxiqun** [PX4/ecl#384]
`// Apply limits on the demanded rate of change of speed based on physical performance limits
	// with a 50% margin to allow the total energy controller to correct for errors.
	float velRateMax;
	float velRateMin;

	if ((_uncommanded_descent_recovery) || (_underspeed_detected)) {
		velRateMax = 0.5f * _STE_rate_max / _tas_state;
		velRateMin = 0.5f * _STE_rate_min / _tas_state;

	} else {
		velRateMax = 0.5f * _STE_rate_max / _tas_state;
		velRateMin = 0.5f * _STE_rate_min / _tas_state;
	}`
I think it should not need the "if else",because the one and the other is same.

**Comment by dagar** [comment]
Yes, it's useless like this. Would you like to open a pull request to fix it?

**Comment by LorenzMeier** [comment]
@priseborough Could you have a look? Should we be doing something else here like e.g. in the if() case not multiply by 0.5?

**Comment by priseborough** [comment]
https://github.com/PX4/ecl/pull/386
