### ISSUE TITLE
EKF: Wrong index use in control.cpp

### ISSUE THREAD

**Issue by priseborough** [PX4/ecl#385]
Should be using index 9 for vertical position

https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L659

**Comment by dagar** [comment]
Create short defines (or static constexpr) for these?

**Comment by priseborough** [comment]
We could, but there are 24 states and in the process of changing all the instances we would have a good chance of introducing a flight critical bug.

**Comment by priseborough** [comment]
The use of 8 is a hangover from the original ecl EKF that used 3 states for attitude instead of 4.
