### ISSUE TITLE
error in ekf.cpp

### ISSUE THREAD

**Issue by asoharev** [PX4/ecl#400]
Hi
I've read the code and it seems like I've found a bug in the velocity calculations at
lines 361-362:
https://github.com/PX4/ecl/blob/337cdcc59a2df1f5e395c4c27d69748227e90bbd/EKF/ekf.cpp#L361-L362
but _state.vel in Earth frame. I  think you should rotate gravity vector and compensate from full velocity vector.

**Comment by bresch** [comment]
Hi @asoharev ,
The rest of the state velocity vector is compensated here https://github.com/PX4/ecl/blob/337cdcc59a2df1f5e395c4c27d69748227e90bbd/EKF/ekf.cpp#L359 using rotated acceleration (https://github.com/PX4/ecl/blob/337cdcc59a2df1f5e395c4c27d69748227e90bbd/EKF/ekf.cpp#L350).
Then the gravity is removed: `_state.vel(2)` is in earth frame, as well as `_gravity_mss` (1g constant). I don't see where the mistake is.

**Comment by asoharev** [comment]
I'm sorry, my fault. I understand, EF = NED. 
Before I'd met earth frame as ECEF only (https://en.wikipedia.org/wiki/ECEF) and thought that's generally accepted.

Thanks for your  answer!

**Comment by bresch** [comment]
@asoharev No problem, I agree that it could be quite confusing, I understand why you thought it was wrong then :)
