### ISSUE TITLE
Critical loss of GPS with air data aiding issue

### ISSUE THREAD

**Issue by priseborough** [PX4/ecl#414]
When GPS is lost and sideslip and airspeed estimation is enabled, the EKF continues to navigate using the wind and sideslip fusion to constrain velocity drift. SITL testing has shown that stability of the air data fusion is inadequate and numerical errors accumulate until air data can no longer be fused. 

![screen shot 2018-03-26 at 12 23 28 pm](https://user-images.githubusercontent.com/3596952/37882785-002a78be-30f2-11e8-9268-fbc236998977.png)

Detected during testing of https://github.com/PX4/Firmware/pull/8771

Preliminary inspection of the SITL log data indicates that this is caused by poor conditioning of the covariance matrix. The following areas need to be reviewed:

1) Wind state process noise
2) Constraint of covariance values
3) Equations and logic for fusion of sideslip and airspeed

**Comment by priseborough** [comment]
Fixed by https://github.com/PX4/ecl/pull/413

**Comment by thomasgubler** [comment]
➤ Paul Riseborough commented:

https://github.com/PX4/ecl/pull/413 has been merged
