### ISSUE TITLE
Possible improvement in position valid operation

### ISSUE THREAD

**Issue by langxm1223** [PX4/ecl#415]
Hello, I am running px4 with v1.7.3 and the associated EKF.
I tested it in GPS denied environment with only range finder and optical flow available.
I found that for some time my flow cannot have a good quality, e.g. no texture, then the xy_valid would turn to false as designed. However, in this invalid interval, states are still self propogating with IMU data without any xy direction sensor. So the result is, after several seconds when there is texture again, the position would be suddenly pop up to several meters away from the normal range.
I wonder if this is designed or I missed some settings.
The following is an example, with a sudden change to 10 meters at last.
![ekf_flow1](https://user-images.githubusercontent.com/4576753/37964082-d8137ba8-31f2-11e8-8133-63a9e2b7b0cf.png)

Thanks.

**Comment by priseborough** [comment]
This is expected. The ability to do inertial dead reckoning without external aiding (eg GPS or optical flow) is very limited with cheap MEMS sensors.
