### ISSUE TITLE
elseif never reached

### ISSUE THREAD

**Issue by bartslinger** [PX4/ecl#430]
Was going through the code and noticed that this is never called:
https://github.com/PX4/ecl/blob/master/EKF/ekf.cpp#L221

Because of https://github.com/PX4/ecl/pull/388

Not exactly sure yet what the implication is.

**Comment by ChristophTobler** [comment]
@bartslinger I guess you are right. That got forgotten in https://github.com/PX4/ecl/pull/388
Can you create a PR?

**Comment by bartslinger** [comment]
Sure, just didn't do it yet because I'm not 100% sure if removing it was the correct solution. PR is here https://github.com/PX4/ecl/pull/431
