### ISSUE TITLE
coordinated turn calculation error

### ISSUE THREAD

**Issue by yuxiqun** [PX4/ecl#443]
In 'PX4/ecl//attitude_fw/ecl_yaw_controller.cpp', there is may be an error:
`if (!inverted) {
 /* Calculate desired yaw rate from coordinated turn constraint / (no side forces) */
 _rate_setpoint = tanf(constrained_roll) * cosf(ctl_data.pitch) * CONSTANTS_ONE_G / (ctl_data.airspeed <
 ctl_data.airspeed_min ? ctl_data.airspeed_min : ctl_data.airspeed);
 }
`
I think it should be:
_rate_setpoint = tanf(constrained_roll) * CONSTANTS_ONE_G / (ctl_data.airspeed <
 ctl_data.airspeed_min ? ctl_data.airspeed_min : ctl_data.airspeed).

**Comment by bresch** [comment]
Hello. Your expression is simply an approximation when the pitch angle is small. The equation implemented in ecl is perfectly correct.

See here for more details: https://books.google.ch/books?id=XIabCgAAQBAJ&pg=PA342&lpg=PA342&dq=turn+coordination+constraint&source=bl&ots=EpdLxclPSv&sig=UgO6DlWNnSK6ZMk_0vZnR9ZPO_w&hl=fr&sa=X&ved=0ahUKEwi1zcvpoIrbAhVFY1AKHYCWAM0Q6AEIMzAB#v=onepage&q=turn%20coordination%20constraint&f=false
