### ISSUE TITLE
how to get Jaccobian L in WindEstimator::initialise

### ISSUE THREAD

**Issue by InerNavy** [PX4/ecl#487]
"compute jacobian of states wrt north/each earth velocity states and true airspeed measurement", i am confused about how to get the jacobian L，when the state is w_n, w_e, tas, and the state equation is w_n = v_n - tasMeas * cos(atan(v_e, v_n)), to get jacobian about the states, i can not get L, so about this part, i hope that you can give a more specific interpretion,many thanks

**Comment by priseborough** [comment]
replace the atan with tan(ve/vn) and you will be able to compute the partial derivative. The sign of the derivative be correct for all quadrants
