### ISSUE TITLE
pmw3901 optical flow not working?

### ISSUE THREAD

**Issue by kyuhyong** [PX4/ecl#509]
Today I tried to use pmw3901 optical flow sensor instead of px4flow. 
This sensor is smaller and lighter but gives enough position estimate for crazyflie however it does not seem to be working with pixhawk or more specifically px4fmu-v2_default build. 

I followed below modifications to utilize the sensor and checked OPTICAL_FLOW integrated x and y data is streaming.
https://github.com/PX4/Firmware/commit/a936dc291eac4e368b1a9c771fdbcbc32449753a
When ekf2 start, I also found optical flow message is fed into the ekf. 

So I tried to fly with this setup but could not even get the altitude hold mode working as below log shows.
https://logs.px4.io/plot_app?log=71b0c931-de42-47f1-8933-b177f3dcf26d

Put the drone into position hold mode was even worse. 
Everything worked perfect with px4flow before and now it doesn't. 
What am I doing wrong? or pmw3901 is not suitable for current 1.8.0 version of ekf2?
Any help would much appreciated. 

Kyu

**Comment by ChristophTobler** [comment]
You are using an old version which is missing https://github.com/PX4/Firmware/pull/10339 this fix.
Feel free to reopen if you have issues with the current master
