### ISSUE TITLE
While on position hold with OF aid, drone moves sideways.

### ISSUE THREAD

**Issue by kyuhyong** [PX4/ecl#513]
Hello,
I am testing optical flow aided position hold for indoor navigation and found weird behavior. 
When setpoint is set and not moving, drone tends to move left (side way). 
Looking at the log, it does not show any movements.
https://logs.px4.io/plot_app?log=f00136e9-fabc-4fa2-80d9-56d4c2ec3be2
![positionhold_localposition](https://user-images.githubusercontent.com/22294429/45664483-f528d980-bb46-11e8-9e94-2821a1fb94b8.png)

However when integrates flow int X and Y, it clearly shows movements in x direction (flow x = side ways) while not much movement in Y direction (Front and back)
![position_flowint](https://user-images.githubusercontent.com/22294429/45664547-5b156100-bb47-11e8-8efb-8782d1ffb464.png)
This happens everytime it flies. 

I tried change EKF2_OF_N_MAX or EKF2_OF_N_MIN but no clear improvements. 
Any suggestions or help would be much appreciated. 

Kyu

**Comment by priseborough** [comment]
This is not the correct forum to ask for integration assistance. Please move to http://discuss.px4.io
