### ISSUE TITLE
Consolidate use of mag declination lookup tables

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#523]
The lookup tables used to generate the "true" magnetic declination [in Gazebo](https://github.com/PX4/sitl_gazebo/blob/2adc86b5bf84543091470966caf33c3b4f3ee666/src/geo_mag_declination.cpp#L57) and the tables in the [ECL library](https://github.com/PX4/ecl/blob/master/geo_lookup/geo_mag_declination.cpp#L61) does not return the same values. E.g. if you run a SITL mission in 
```
 // Port-aux-Francais (-55 deg declination): -49.350330, 70.219162
  double lat_home = -49.350330 * M_PI / 180; // rad
  double lon_home = 70.219162 * M_PI / 180; // rad
  double alt_home = 10.0; // meters
```

The SITL lookup tables will return -57.8687 degrees and the tables in ECL will return -44.1178 degrees. This results in a ~10 degree heading error at bootup.

We should figure out which tables are most accurate and switch to only use those

**Comment by dagar** [comment]
Update the sitl_gazebo tables to match ecl? We updated the ecl side earlier this year. https://github.com/PX4/ecl/commit/39b69af9bf8340790011c7c2723d4ed725ea0a3b#diff-55f02734c9f6c25271536a1feecb6b35

**Comment by dagar** [comment]
Yes, but it would probably be a little awkward unless we broke it out into a standalone project. In this particular case I think it would be fine to manually duplicate.

**Comment by CarlOlsson** [comment]
The mag declination tables have now been updated in SITL Gazebo
