### ISSUE TITLE
High susceptibility to noisy mag data

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#525]
At bootup we filter the mag measurements and then use the filtered value to initialize the earth magnetic field measurements, and if [this is merged](https://github.com/PX4/ecl/pull/524), also to initialize the heading.

However, as soon as we get GPS lock we again reinitialize the earth magnetic field states and heading, this time without filtering. The same is true also for the reinitializiation of the heading at every takeoff if EKF2_MAG_TYPE = 0 (automatic switching between heading and 3D axis mag fusion).

The obvious issue here is that two times every flight the raw value of the magnetometer is super important. There is no auto rejection of these samples, so if they are wrong the heading and mag states can be arbitrary far away from reality.

We of course also use the raw sensor measurement from e.g. GPS every time we reset the vel/pos states, but that should mostly happen if something is wrong, not every flight as is the case with the mag.

**Comment by dagar** [comment]
This is probably crude, but the cost of running the mag filter continuously would be minimal. 

![image](https://user-images.githubusercontent.com/84712/48868109-8d8d4580-eda6-11e8-8bf1-4b0ef91681f3.png)

**Comment by CarlOlsson** [comment]
For vehicles using EKF2_MAG_TYPE = 1 (only heading fusion) this is now even worse.
Since https://github.com/PX4/ecl/pull/544 we reinitialize the earth magnetic field states at takeoff and start using them for calculating the declination. If that single magnetometer sample that is used for this is bad the declination will be off and there is no way for the EKF to recover since the earth field states are not even estimated
