### ISSUE TITLE
*feature request* warn user if Compass declared bad

### ISSUE THREAD

**Issue by Antiheavy** [PX4/ecl#526]
Request:
Improve the text of this ECL_WARN message and add it as a mavlink_log_critical warning so that the user sees it and knows there was a problem that was resolved in flight and should be checked into after landing.

https://github.com/PX4/ecl/blob/c49ab760c78fc6dc4cb174d6f9b7b39b01e19a7b/EKF/ekf_helper.cpp#L433

Suggested new text of a **mavlink_log_critical** message:
"Stopping compass use, check calibration on landing"
or
"Compass fault, stopping use, check calibration"

I don't understand ECL architecture well enough to know if this mavlink_log_critical message can live here or if it needs to be in PX4/Firmware too.

@priseborough thoughts?

**Comment by priseborough** [comment]
This event is detectable outside the EKF by monitoring bit position 18 of the estimator_status.control_mode_flags message. I would check for this bit transitioning to high in Commander::estimator_check(...) function and add the messaging via mavlink_log_critical there.
