### ISSUE TITLE
EKF: Bug in yaw reset variance calculation

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#548]
In resetMagHeading() in ekf_helper.cpp we use the angular error of the last external vision measurement when we calculate the angular error variance vector even if external vision is not activated.

https://github.com/PX4/ecl/blob/4822bf83861513cf330ab1482439ed1c72e99232/EKF/ekf_helper.cpp#L732-L739

The bug seems to have been introduced [here](https://github.com/PX4/ecl/commit/389786ef1bbac0d1844348e0539bf23aea319786#diff-6ff089a846fa4bd452bf076e28a0bef7)

**Comment by priseborough** [comment]
I'll raise a PR for this. It's a quick fix.
