### ISSUE TITLE
Earth mag state covariances are initialized to 0

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#554]
@priseborough the issue you are referring to [here](https://github.com/PX4/ecl/issues/541#issuecomment-455047530) is not a problem with the new quaternion covariance reset branch but a bug on master.

It was introduced [here](https://github.com/PX4/ecl/pull/544) and happens because when mag_align_complete is set to true [here](https://github.com/PX4/ecl/blob/721f5e61a5965a08a34b2875d2bdc0b5d3b80601/EKF/control.cpp#L1376-L1376) the saved_mag_variance is not updated [here](https://github.com/PX4/ecl/blob/721f5e61a5965a08a34b2875d2bdc0b5d3b80601/EKF/control.cpp#L1477-L1477) so the mag field states are overwritten to zero the first time we activate 3D mag fusion [here](https://github.com/PX4/ecl/blob/721f5e61a5965a08a34b2875d2bdc0b5d3b80601/EKF/control.cpp#L1464-L1464) 

One way of solving this is to force 3D fusion for a short time right after takeoff, something a proposed a while back ago [here](https://github.com/PX4/ecl/pull/533)

**Comment by priseborough** [comment]
Fixed in https://github.com/PX4/ecl/pull/556
