### ISSUE TITLE
Initial magnetometer alignment is never performed by GPS CoG 

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#557]
Issue was first raised [here](https://github.com/PX4/ecl/issues/541#issuecomment-456085210) but I thought it would be best to create a separate issue not to lose track of it.

The code that enables planes to recover from bad mag data at start of flight that was added [here](https://github.com/PX4/ecl/pull/294) is never triggered anymore since the yaw reset by magnetometer that was added [here](https://github.com/PX4/ecl/pull/544) always runs before.

https://github.com/PX4/ecl/blob/ad9414e4dadc6a7a25d33b7edc219775d8a88086/EKF/control.cpp#L1455-L1470

**Comment by priseborough** [comment]
Testing passed. See https://github.com/PX4/ecl/pull/556#issuecomment-459105502 for details.

**Comment by mhkabir** [comment]
Fixed on master.
