### ISSUE TITLE
Error in estimator_interface.h

### ISSUE THREAD

**Issue by Slimercorp** [PX4/ecl#566]
estimator_interface.h:
127-131 lines:

	// gets the innovation variance of the HAGL measurement
	virtual void get_hagl_innov_var(float *flow_innov_var) = 0;

	// gets the innovation of the HAGL measurement
	virtual void get_hagl_innov(float *flow_innov_var) = 0;
must be hagl_innov & hagl_innov_var

**Comment by mhkabir** [comment]
Can you send a PR for this?Thanks!

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/ecl/pull/611
