### ISSUE TITLE
error:Running Matlab scripts for generate navfilter equation

### ISSUE THREAD

**Issue by velan45** [PX4/ecl#568]
Hi
I tried to run matlab script for generating navfilter equations, but I am getting this error 
![matlab script](https://user-images.githubusercontent.com/30148049/52162172-f45ba300-26f5-11e9-9bc0-8e031f798e26.png)
any kind of help would be greatly appreciated. Thanks

**Comment by dagar** [comment]
Which version of matlab? I believe @priseborough was last using ~ 2015b.

**Comment by priseborough** [comment]
I have been told the scripts do not work on the current version and I do not have the latest version you are using so am unable to fix.
