### ISSUE TITLE
Only 3D mag fusion is broken

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#575]
If `EKF2_MAG_TYPE = 2` (only 3D mag fusion) the estimator will continuously trigger yaw resets
https://github.com/PX4/ecl/blob/1378ec179717448404c74819871d149217350b19/EKF/control.cpp#L1542-L1545

since mag_align_complete is set to false here
https://github.com/PX4/ecl/blob/1378ec179717448404c74819871d149217350b19/EKF/control.cpp#L1378-L1378

To reproduce run
`make px4_sitl gazebo`, set `EKF2_MAG_TYPE = 2` and restart simulation

![image](https://user-images.githubusercontent.com/7795133/53489382-57402000-3a91-11e9-88ea-2f418edab1de.png)
![image](https://user-images.githubusercontent.com/7795133/53489415-69ba5980-3a91-11e9-9903-cca3a2dc80fd.png)

**Comment by dagar** [comment]
Any idea when it was last functional?

**Comment by CarlOlsson** [comment]
No, I never used it before. Just wanted to test something in SITL and noticed that the vehicle never got GPS lock
