### ISSUE TITLE
Docs: link broken

### ISSUE THREAD

**Issue by julianoes** [PX4/ecl#576]
The link in the readme for "EKF Documentation and Tuning Guide" does not work anymore.
FYI @hamishwillee

**Comment by julianoes** [comment]
It's still here:
https://github.com/PX4/px4-devguide/blob/master/en/tutorials/tuning_the_ecl_ekf.md
and here:
https://web.archive.org/web/20180619060008/https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.html

**Comment by hamishwillee** [comment]
Hi @julianoes 

The doc moved into the user guide: https://docs.px4.io/en/advanced_config/tuning_the_ecl_ekf.html
I created a redirect from the devguide https://dev.px4.io/master/en/tutorials/tuning_the_ecl_ekf.html
Unfortunately the master build did not propagate into the root, so if you go to https://dev.px4.io/en/tutorials/tuning_the_ecl_ekf.html you don't get that redirect.

The source for the devguide is here: https://github.com/PX4/Devguide

I have no idea what https://github.com/PX4/px4-devguide - the link you provided is. Can we tell who created it? Can it be deleted. @dagar do you know about this one?

**Comment by mrpollo** [comment]
Can we fix the link in the README to point to the new location? this will fix the README

**Comment by dagar** [comment]
No idea where https://github.com/PX4/px4-devguide came from. Should we get rid of it?

**Comment by hamishwillee** [comment]
> Should we get rid of it?

@dagar Yes please. I don't have the permissions.

**Comment by dagar** [comment]
> > Should we get rid of it?
> 
> @dagar Yes please. I don't have the permissions.

Done

**Comment by hamishwillee** [comment]
Thanks. We still need to fix issues with the root not being updated :-)
