### ISSUE TITLE
TODO Add contributing instructions for this library

### ISSUE THREAD

**Issue by tstellanova** [PX4/ecl#589]
Might include a checklist such as:
- Run [astyle](https://github.com/PX4/Firmware/tree/master/Tools/astyle) to ensure consistent code style
- Add unit tests if code can be covered by unit tests
- Add doxygen documentation headers to new code

https://github.com/PX4/ecl/blob/4e0e68e905e655790b52b79bcbc4225242a2df43/CONTRIBUTING.md#L1

**Comment by dagar** [comment]
The reason astyle isn't currently enforced is that the generated code in the EKF doesn't format well. Ideally we'd break that out into separate files instead of mixing it in with real hand written code.

**Comment by kamilritz** [comment]
Except for the doxy header generation, this seems now added.
