### ISSUE TITLE
Replay conversion script outdated: baro and mag missing from sensor_combined

### ISSUE THREAD

**Issue by jbeyerstedt** [PX4/ecl#595]
I tried to run [EKF/matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m ](https://github.com/PX4/ecl/blob/master/EKF/matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m), but this does not work any more.

```
Undefined function or variable 'baro_timestamp_relative'.
```

When taking a close look, all baro and mag data is missing from the imported CSV file.
baro_timestamp_relative.
If I identified it correctly, https://github.com/PX4/Firmware/commit/3b5b12e1d16b9c603aaa920f0f1ea96f6848f3db (from 2019-02-18) introduced the changes, which break this script.

**Comment by priseborough** [comment]
Yes, you would need to use an earlier version of firmware to generate a compatible log. Feel free to submit a PR that fixes https://github.com/PX4/ecl/blob/master/EKF/matlab/EKF_replay/Common/convert_px4_sensor_combined_csv_data.m

**Comment by jbeyerstedt** [comment]
I have a patched the script for now, but I don't have the time now to submit a pull request.
Because I also created some additional scripts to automate the whole process by running a bash script calling Matlab from the command line. And ground truth data will also be imported.
But the bash script is quite specific to my use case for now and will also only find the Matlab executable for a single Matlab version and on macOS. So it's not ready to be released yet.

In about 8 weeks, when my thesis is done, I can take a look at this again.
