### ISSUE TITLE
Error in ekf_helper.cpp

### ISSUE THREAD

**Issue by ecpknpaul** [PX4/ecl#604]
Hi:
ekf_helper.cpp:
line 512:
`// Note q1 *= q2 is equivalent to q1 = q2 * q1 `
I think it should be `q1 *= q2 is equivalent to q1 = q1 * q2`, because in file Quaternion.hpp, line 272-276:

> void operator*=(const Quaternion &other)
 {
 Quaternion &self = *this;
 self = self * other;
 }

and I think in file ekf_helper.cpp, line 519
`_output_new.quat_nominal = _state_reset_status.quat_change * _output_new.quat_nominal;`
should be:
`_output_new.quat_nominal = _output_new.quat_nominal * _state_reset_status.quat_change;`

Am I right？Looking forward to your reply.

**Comment by CarlOlsson** [comment]
Hi,

yes you are right! I forgot to fix those lines in [this PR](https://github.com/PX4/ecl/pull/586)
I did not notice since it was not visible in the logs since the error only affects one single output.
How did you find it? 
I pushed a fix [here](https://github.com/PX4/ecl/pull/605)

**Comment by ecpknpaul** [comment]
Hi,
I just read the code,  and find the quaternion multiplication is in the wrong order.

**Comment by priseborough** [comment]
Yes, the comment and code are inconsistent and we should be using the same convention for multiplication order as the Eigen library. Please provide log evidence of the error because if the order is wrong it should be visible in a log.
