### ISSUE TITLE
Last known position in controlVelPosFusion not updated properly

### ISSUE THREAD

**Issue by AtharvPawar** [PX4/ecl#617]
In `control.cpp`, in the following lines within the `controlVelPosFusion()` function:
https://github.com/PX4/ecl/blob/a036cf82cc92ef6572ea7ee960cfff4d305c01fa/EKF/control.cpp#L1654-L1655

The variable `_last_known_posNE` is updated only in `controlOpticalFlowFusion()`, in these lines:
https://github.com/PX4/ecl/blob/a036cf82cc92ef6572ea7ee960cfff4d305c01fa/EKF/control.cpp#L515-L516

Otherwise it would stay at 0 (the initialization value). This could potentially cause the innovations to rise rapidly if we are not using optical flow. Am I missing something or is this a bug?

**Comment by xdwgood** [comment]
@AtharvPawar  Only when these conditions are met will you enter the calculation of the innovation value you said.  https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L1617-L1620
This means we don't have any valid position measurements.
then here： https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L1625
then here： https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L1629
then here： https://github.com/PX4/ecl/blob/master/EKF/ekf_helper.cpp#L177

```
_state.pos(0) = _last_known_posNE(0);
_state.pos(1) = _last_known_posNE(1);
```

So this means that the innovation value will be calculated as 0 and will not increase indefinitely.

The positional innovation when using gps is calculated here:https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L683

```
_vel_pos_innov[3] = _state.pos(0) - _gps_sample_delayed.pos(0);
_vel_pos_innov[4] = _state.pos(1) - _gps_sample_delayed.pos(1);
```

According to my personal understanding, I prefer to set this innovation value to 0.



```
ecl/EKF/control.cpp
Lines 1654 to 1655 in a036cf8
 _vel_pos_innov[3] = 0.0f; 
 _vel_pos_innov[4] = 0,0f; 
```

@priseborough  should know more, why do it..   :smiley: 
Welcome to correct any errors of mine.  :smiley:
