### ISSUE TITLE
GPS heading fusion does not block mag heading fusion

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/ecl#625]
From the parameter documentation I understand that with GPS heading enabled, and mag fusion set to automatic, the mag yaw should only be used until the GPS heading is available. But for that I think there is a condition missing similar to the one already in place for EV heading fusion in https://github.com/PX4/ecl/blob/master/EKF/control.cpp#L1377, otherwise the mag fusion is re-enabled right after GPS heading fusion disables it (and they will both run).

I'd appreciate if someone can clarify that this is the general idea behind it. Also, heading fusion never falls back to mag if GPS becomes unavailable?

**Comment by AndreasAntener** [comment]
If we assume magnetometer values are not safe to use in certain areas we don't want it use both or fall back to mag.

What happens if GPS heading is not updated anymore for a long time? This case is not explicitly handled yet as far as I can see. It seems to just continue integrating the gyro.

**Comment by AndreasAntener** [comment]
This is from a bench test, you can see the innovation spikes which have roughly the length of the difference between mag and GPS heading. With MAG_TYPE 0. I don't think that's the idea.

<img width="1375" alt="Screenshot 2019-07-31 at 09 28 59" src="https://user-images.githubusercontent.com/5750020/62192490-02714000-b376-11e9-9e8b-14ead86d4f61.png">

**Comment by RomanBapst** [comment]
@AndreasAntener As far as I know gps heading was tested but I don't think the logic is complete (as you have correctly stated). Do you have a replay log available which I could use to test some changes?
I do have a setup in the office in case you don't have one available. During the replay I can stop gps data to make sure that it switches over between gps and mag correctly.

**Comment by AndreasAntener** [comment]
No replay log yet. Trying to reproduce locally. Similar issue like Paul reported occurs as well: https://github.com/PX4/ecl/issues/627

I will push the small change I did, which makes it switch correctly as far as I can see, and it works well, but we many times we have a drift initially which won't come to rest.

**Comment by AndreasAntener** [comment]
Issue reproduced on PX4 1.9.2: https://review.px4.io/plot_app?log=703082d0-c57f-40a8-bdd4-5194de2233f5

![Screenshot 2019-08-08 at 15 02 24](https://user-images.githubusercontent.com/5750020/62705390-9d5cc080-b9ed-11e9-9233-45d57bec38ca.png)

**Comment by priseborough** [comment]
The decision to not fall back to mag was deliberate. In the case where loss of GPS is extended, heading will dead reckon using gyro, but horizontal velocity vector changes will make it observable and apply corrections. I need to check that we have protection against the growth in yaw uncertainty resulting in the covariance matrix becoming badly conditioned. There is an exisiting method to prevent this for the case where we operate without a yaw sensor, eg when EKF2_MAG_TYPE = 4, see https://github.com/PX4/ecl/pull/628. 

The same method can be used to protect against bad conditioning of the covariance matrix for extended loss of GPS yaw when GPs heading is enabled.

**Comment by priseborough** [comment]
I've merged https://github.com/PX4/ecl/pull/629 becasue it fixes the logic bug, but have left the issue open until the yaw drift and covariance conditioning questions have been answered.

**Comment by priseborough** [comment]
The code now checks for quaternion variance growth in the fuseHeading() function when yaw fusion is inhibited and if too large, fuses a zero innovation yaw observation.
