### ISSUE TITLE
External vision velocity estimate usage

### ISSUE THREAD

**Issue by kamilritz** [PX4/ecl#631]
From the vehicle_visual_odometry msg only the position estimate is used at the moment. Current VIO systems, such as the Realsense T265, output also a velocity estimates. It could be interesting to enable the EKF to also handle EV velocities, since these are likely to be continuous. While the position estimate from the EV system can include jumps due to re-localization or loop-closures. 

I would be happy to investigate this further.

**Comment by mhkabir** [comment]
I'm working on this right now.

**Comment by mhkabir** [comment]
Done!
