### ISSUE TITLE
Quaternion covariance is not zeroed before yaw reset changes are applied.

### ISSUE THREAD

**Issue by priseborough** [PX4/ecl#632]
Although we modify the off diagonals in the increaseQuatYawErrVariance(...) function to  account for the increased uncertainty when doing a yaw reset, we don't reset them to zero before doing so with the result that prior correlation information which is no longer valid has been preserved.

This appears to be incorrect.

**TODO:** 

Check code and test with large yaw reset with and without a prior zero of the quaternion covariance sub-matrix off-diagonals.

Issue raised here: https://px4.slack.com/archives/C643UJTB7/p1565270983019100

**Comment by kamilritz** [comment]
@priseborough any update here?

**Comment by priseborough** [comment]
We either call initialiseCovariance or  uncorrelateQuatFromOtherStates functions prior
