### ISSUE TITLE
Integrator scaling factor (roll/pitch controllers)

### ISSUE THREAD

**Issue by hannahdn** [PX4/ecl#633]
In the [controller doc ](https://dev.px4.io/v1.9.0/en/flight_stack/controller_diagrams.html), it is said:

> The output of the rate PI controller has to be scaled with the indicated airspeed (IAS) squared

However in the rate controller (roll and pitch), the integral term is scaled with IAS, not IAS squared. 

```	
/* Apply PI rate controller and store non-limited output */
_last_output = _bodyrate_setpoint * _k_ff * ctl_data.scaler +
_rate_error * _k_p * ctl_data.scaler * ctl_data.scaler
+ _integrator;  //scaler is proportional to 1/airspeed
```

Why is that?

**Comment by hamishwillee** [comment]
@bresch ^^^^
