### ISSUE TITLE
【Question】Do we need a stricter gps check?

### ISSUE THREAD

**Issue by xdwgood** [PX4/ecl#659]
issue： https://github.com/PX4/Firmware/issues/13279
Currently we have completed the gps check in this function:`
bool Ekf::gps_is_good(const gps_message &gps)`  

We use eph, epv to check the position drift. There is a problem here. The eph and epv conditions that we set by default are easy to satisfy.

In the https://github.com/PX4/Firmware/issues/13279 problem: the latitude and longitude data drift provided by the gps module causes the ekf to estimate the local position drift, but in fact the autopilot is not moved.
![Screenshot from 2019-10-28 14-48-43](https://user-images.githubusercontent.com/24932258/67657556-0f5ff880-f992-11e9-93a9-2e367fdc8e1e.png)

For me, I might be able to adjust the process noise of gps and reduce the trust in gps data in the position estimate.
But for a customer, if he takes off directly in this state, the drone position will drift，right?

I wonder if we should restrict eph, epv more strictly, or add a position drift detection when the drone is still on the ground.

Any reply or criticism is welcome

**Comment by mhkabir** [comment]
Already implemented. See https://github.com/PX4/Firmware/issues/9549.

**Comment by xdwgood** [comment]
I am already using the latest master branch, but local.x/y is still drifting when the autopilot is still on the ground.There are also no warnings preventing me from entering position mode.

**Comment by RomanBapst** [comment]
@xdwgood It's up to you if you want to have stricter checks on the gps data.
Have a look at his table [here](https://docs.px4.io/master/en/advanced_config/tuning_the_ecl_ekf.html#gps-performance-requirements)
It describes the different parameters you can use to achieve your goals. You can actually specify a maximum drift rate.
