### ISSUE TITLE
Rewrite EKF symbolic derivations in sympy

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#667]
Just realized that I can't run `GenerateNavFilterEquations.m` since I don't have access to the MATLAB symbolic toolbox anymore.
I guess I am not alone so we should rewrite it in sympy
@RomanBapst I remember you mentioning that you already started?

**Comment by mhkabir** [comment]
This would be awesome.

**Comment by RomanBapst** [comment]
@CarlOlsson Yep, I can share what I've started.

**Comment by bresch** [comment]
@RomanBapst Can you share what you currently have?

**Comment by dagar** [comment]
Done!
