### ISSUE TITLE
Velocity and position test ratios are not logged correctly on PX4 v1.10-rc

### ISSUE THREAD

**Issue by CarlOlsson** [PX4/ecl#682]
Here are velocity and position test ratios from PX4 v1.10 release candidate (from a random logfile I found on review.px4.io).
The upper is the release candidate and the lower is a logfile collected with an older version of ECL for comparison
![image](https://user-images.githubusercontent.com/7795133/70717788-5d854d00-1cef-11ea-8f2d-2d1d059be89a.png)

As can be seen the upper is useless. Running a SITL mission with max logging frequency of the estimator_status on the release candidate shows spikes in the test ratios at 5 HZ
(again RC vs comparison)
![image](https://user-images.githubusercontent.com/7795133/70718002-b8b73f80-1cef-11ea-8490-7e8890d97125.png)

Plotting the test ratio and the innovations shows that the test ratio is now reset to zero right after the fusion (upper) while in the past it was not (lower)
![image](https://user-images.githubusercontent.com/7795133/70718135-f4520980-1cef-11ea-9514-c483308f7ce2.png)

**Comment by CarlOlsson** [comment]
@kamilritz Seems like the issue comes from here https://github.com/PX4/ecl/pull/642/commits/e9f6b7140a0e56ad426dc0449d4c9c8aa8a5bbd5

What was the purpose of this change?

**Comment by dagar** [comment]
This should be fixed for v1.10 shortly.

**Comment by dagar** [comment]
Thanks for testing Carl!

**Comment by kamilritz** [comment]
@CarlOlsson The purpose was to have the test_ratio reporting zero after the fusion of a particular sensor is stopped completely. 
You are right `e9f6b71` is causing this. When the `fuseVelPosHeight()` function is called with only `_fuse_height = true` it sets the `pos_test_ratio` and `vel_test_ratio` accidentally to zero.
This is a clear bug. 
I created a branch with a fix for the release. @dagar is getting it into the release.

@CarlOlsson Thank you very much catching this!

FYI @priseborough

**Comment by CarlOlsson** [comment]
> @CarlOlsson Thank you very much catching this!

No problem :) We started to work on a rebase on v1.10 so will do a lot of testing

**Comment by dagar** [comment]
Fixed in https://github.com/PX4/Firmware/pull/13736.
