### ISSUE TITLE
Stop mag heading fusion if yaw stays at +/-90 deg

### ISSUE THREAD

**Issue by kamilritz** [PX4/ecl#705]
While I wrote a unit test, I noticed that when we set the orientation exactly to +/- 90 degrees that the heading uncertainty is increasing until it hits the limits. I followed it down to these [lines of code](https://github.com/PX4/ecl/blob/master/EKF/mag_fusion.cpp#L533-L537). Since in practice we will never stay exactly so close to +/- 90 degrees we will not always return before triggering the fusion. But if we do, we stop performing heading fusion.

@RomanBapst @priseborough FYI

**Comment by mhkabir** [comment]
I wonder if this can also happen if you're using external vision which initializes to such an heading angle.

I still have't conclusively tracked down https://github.com/PX4/ecl/issues/698, and then there also was someone else reporting this: https://github.com/PX4/Firmware/issues/13116.
