### ISSUE TITLE
EKF2 vertical velocity estimate not consistent with change in vertical position during forward flight

### ISSUE THREAD

**Issue by ryankierteal** [PX4/ecl#777]
I have been seeing some strange behavior with the EKF2 vertical velocity and position estimation, and I'm having trouble tracking down the root cause of the issue.

The behavior is an uncommanded increase in altitude during forward flight in position mode.  The estimator is being quite slow to track the changes in the vertical position.  Additionally the estimate of vertical velocity is actually indicating that the drone is going down while both BARO and GPS observations are reporting that the drone is increasing in altitude.
Here is log showing this behavior:
[https://review.px4.io/plot_app?log=441ba346-5f27-4883-8797-4637a8a7f3e0](https://review.px4.io/plot_app?log=441ba346-5f27-4883-8797-4637a8a7f3e0)

The drone is running code forked from v1.10.0
BMI088 ACCEL ODR 400 Hz, BW 40 Hz
BMI088 GYRO ODR 400 Hz, BW 47 Hz
EKF is running at 200 Hz (FILTER_UPDATE_PERIOD_MS = 5) to align with the IMU sampling rates
BMP388 BARO ODR ~44 Hz

I have tried adjusting some of the EKF2 parameters that I thought would have some impact on vertical velocity and vertical position tracking:

Here's a flight where I enabled IMU Bias Estimation (EKF2_AID_MASK = 1, instead of 5):
[https://review.px4.io/plot_app?log=114c5acd-9c05-4b2d-be6c-1fdf89077601](https://review.px4.io/plot_app?log=114c5acd-9c05-4b2d-be6c-1fdf89077601)

Here's a flight with IMU Bias Estimation enabled and EKF2_BARO_NOISE = 0.5 m (instead of default 2.0 m):
[https://review.px4.io/plot_app?log=ffcc3f10-fdf3-4f7b-a1d3-cdafc942c339](https://review.px4.io/plot_app?log=ffcc3f10-fdf3-4f7b-a1d3-cdafc942c339)

Here's a flight with IMU Bias Estimation, and EKF2_ACC_NOISE = 1 (instead of default 0.35):
[https://review.px4.io/plot_app?log=8085bae0-c1e0-46ca-aebe-0c4918e9cdff](https://review.px4.io/plot_app?log=8085bae0-c1e0-46ca-aebe-0c4918e9cdff)

Here's a flight with IMU Bias Estimation, EKF2_ACC_NOISE = 1, EKF2_BARO_NOISE = 0.5:
[https://review.px4.io/plot_app?log=983dd971-306a-4ff2-84ff-c038b71335ce](https://review.px4.io/plot_app?log=983dd971-306a-4ff2-84ff-c038b71335ce)

Is there something that I'm missing, or some other parameter I should adjust?

**Comment by priseborough** [comment]
I would recommend you modify the internal EKF update step defined by FILTER_UPDATE_PERIOD_MS to be an integer multiple of the 5msec, ie change it from 8 to 10

**Comment by ryankierteal** [comment]
@priseborough 
> I would recommend you modify the internal EKF update step defined by FILTER_UPDATE_PERIOD_MS to be an integer multiple of the 5msec, ie change it from 8 to 10
Here's a log with FILTER_UPDATE_PERIOD=10.   In this case the BMP388 BARO data is at 22 Hz, and EKF2_AID_MASK = 5:
[https://review.px4.io/plot_app?log=71ace796-7611-4dfe-af0d-0f2f34ba214a](https://review.px4.io/plot_app?log=71ace796-7611-4dfe-af0d-0f2f34ba214a)

**Comment by priseborough** [comment]
Looks like clipping of the Z accel - evidenced by both vertical velocity and position innovations diverging in a positive direction.
![Screen Shot 2020-04-30 at 6 13 17 pm](https://user-images.githubusercontent.com/3596952/80687871-4b754100-8b0e-11ea-976b-87c9e17ecdd3.png)

Also these correlate to high forward speed and pitching moment due to blade flap - see how front/rear ESC demands go low/high to counteract pitching moment
![Screen Shot 2020-04-30 at 6 14 31 pm](https://user-images.githubusercontent.com/3596952/80688048-94c59080-8b0e-11ea-8b06-8f133741ac41.png)

<img width="1123" alt="Screen Shot 2020-04-30 at 6 17 36 pm" src="https://user-images.githubusercontent.com/3596952/80688283-e706b180-8b0e-11ea-9b45-c8289fe058e3.png">

**Comment by ryankierteal** [comment]
Thanks for taking the time to do a detailed analysis @priseborough!
