### ISSUE TITLE
EKF does emergency yaw reset after intermittent gps data

### ISSUE THREAD

**Issue by RomanBapst** [PX4/ecl#804]
Suppose the gps driver stops publishing gps data for 10 seconds and then continues publishing after that. In that case gps position and velocity fusion have timed out and the estimator will perform a combined vel/pos and yaw reset. Also, it will not use magnetometer data anymore, having declared a yaw emergency reset.

Would it make sense to not perform the yaw reset in case the cause of the gps fusion timeout was caused by intermittent gps data?

The plot below shows such a scenario in which gps data times out for a while.
![image](https://user-images.githubusercontent.com/7610489/80372216-d7cbfd80-889b-11ea-9c87-bbcb06644152.png)

**Comment by priseborough** [comment]
It would make sense to not do the reset in those circumstances. I will modify the check to handle that case.
