### ISSUE TITLE
Wind Estimator issue 

### ISSUE THREAD

**Issue by moreba1** [PX4/ecl#885]
Hi

During flight wind calculted value does not correlate with sidelslip angle. 

https://github.com/PX4/Firmware/issues/15508

**Comment by bresch** [comment]
In PX4/Firmware#15508 we came to the conclusion that your setup is having mag issues, please check that before opening issues. You can find what you need in the logs, your heading isn't healthy, so the issues you find with sideslip fusion and the wind estimator are irrelevant:
![2020-08-10_13-34-29_01_plot](https://user-images.githubusercontent.com/14822839/89778760-588ecc80-db0e-11ea-9e94-64a2e924d036.png)
