### ISSUE TITLE
EKF2 vertical height diverged

### ISSUE THREAD

**Issue by tumbili** [PX4/ecl#91]
Happened on a test flight with wing wing and Pixracer

http://logs.uaventure.com/view/EDXp7BmVQsSsboydZMKVWW

First insights from discussion with @priseborough:
- [ ] when local position state is reset the corresponding velocity states needs to be reset as well (not the case now)
- [ ] the high innovations and the resulting divergence of the vertical position could have been caused by timing issues (need to check the performance results)

**Comment by priseborough** [comment]
https://github.com/PX4/ecl/pull/92

**Comment by priseborough** [comment]
I have tested its ability to recover from temporary large errors on IMU z accel data. However we need to give more thought to the desired system behaviour during a height sensor timeout and immediately following a reset.

**Comment by priseborough** [comment]
I have incorporated furthers changes to height reset behaviour here and am i the process of testing it:

https://github.com/priseborough/ecl/tree/pr-ekf2HeightReset

We need a means of inducing sensor faults in SITL
